const LOAD_USERS = 'LOAD_USERS';
const LOAD_SINGLE_USER = 'LOAD_SINGLE_USER';
const LOAD_POSTS = 'LOAD_POSTS';
const LOAD_COMMENTS = 'LOAD_COMMENTS';

export {LOAD_USERS,LOAD_SINGLE_USER,LOAD_POSTS,LOAD_COMMENTS}